### PR TITLE
Logging functionality

### PR DESCRIPTION
**Pull request by Reivals**

### CODE REVIEW

**Comment by pstowski** [comment]
1. Please remove LabEployee & LabDirector, there is User entity for that!
2. Please place tests in src/test not in src/main/test
3. Remove junit dependency with "compile" scope.
4. Please move UserService to services package. 

In repositories: why do you use @Query()? Spring will auto-generate appropriate query for you basing on method name.

**Comment by Reivals** [comment]
Please place tests in src/test not in src/main/test -> It have to be under  src/main/test otherwise intelij don't see it properly. Probably it is configurable but currenty i dont have time for that :P

**Comment by Reivals** [comment]
Other fixes applied

**Comment by pstowski** [comment]
> 
> 
> Please place tests in src/test not in src/main/test -> It have to be under src/main/test otherwise intelij don't see it properly. Probably it is configurable but currenty i dont have time for that :P

First of all it's not intelij project - It's maven project and default place for test is in project/test/java/. Probably it is configurable but there is no need to configure anything. The whole thing is just place tests in right place.

**Pull request merged**
